# Generated by Django 5.1.6 on 2025-05-14 14:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_user_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_pics/default_profile.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
